//! Add noise to images.

use crate::PhotonImage;

#[cfg(feature = "enable_wasm")]
use wasm_bindgen::prelude::*;

#[cfg(all(target_family = "wasm", not(target_os = "wasi")))]
use js_sys::Math::random;

#[cfg(not(all(target_arch = "wasm32", not(target_os = "wasi"))))]
use rand::Rng;

/// Add randomized noise to an image.
/// This function adds a Gaussian Noise Sample to each pixel through incrementing each channel by a randomized offset.
/// This randomized offset is generated by creating a randomized thread pool.
/// **[WASM SUPPORT IS AVAILABLE]**: Randomized thread pools cannot be created with WASM, but
/// a workaround using js_sys::Math::random works now.
/// # Arguments
/// * `img` - A PhotonImage.
///
/// # Example
///
/// ```no_run
/// // For example:
/// use photon_rs::native::open_image;
/// use photon_rs::noise::add_noise_rand;
/// use photon_rs::PhotonImage;
///
/// let mut img = open_image("img.jpg").expect("File should open");
/// add_noise_rand(&mut img);
/// ```
#[cfg_attr(feature = "enable_wasm", wasm_bindgen)]
pub fn add_noise_rand(photon_image: &mut PhotonImage) {
    // Use SIMD optimized version
    add_noise_rand_simd(photon_image);
}

/// Add randomized noise to an image with adjustable strength.
/// This function adds Gaussian noise to each pixel by incrementing each channel by a randomized offset.
/// The maximum offset is controlled by the strength parameter.
/// **[WASM SUPPORT IS AVAILABLE]**
/// # Arguments
/// * `photon_image` - A PhotonImage.
/// * `strength` - Noise strength. Range: 0.0 to 10.0.
///   - 0.0: No noise
///   - 1.0: Subtle noise (max offset 0-15)
///   - 5.0: Moderate noise (max offset 0-75)
///   - 10.0: Strong noise (max offset 0-150, equivalent to add_noise_rand)
///
/// # Example
///
/// ```no_run
/// // For example, to add noise with strength 2.0:
/// use photon_rs::native::open_image;
/// use photon_rs::noise::add_noise_rand_with_strength;
///
/// let mut img = open_image("img.jpg").expect("File should open");
/// add_noise_rand_with_strength(&mut img, 2.0);
/// ```
#[cfg_attr(feature = "enable_wasm", wasm_bindgen)]
pub fn add_noise_rand_with_strength(photon_image: &mut PhotonImage, strength: f32) {
    // Use SIMD optimized version
    add_noise_rand_with_strength_simd(photon_image, strength);
}

/// Add pink-tinted noise to an image.
///
/// **[WASM SUPPORT IS AVAILABLE]**: Randomized thread pools cannot be created with WASM, but
/// a workaround using js_sys::Math::random works now.
/// # Arguments
/// * `name` - A PhotonImage that contains a view into the image.
///
/// # Example
///
/// ```no_run
/// // For example, to add pink-tinted noise to an image:
/// use photon_rs::native::open_image;
/// use photon_rs::noise::pink_noise;
///
/// let mut img = open_image("img.jpg").expect("File should open");
/// pink_noise(&mut img);
/// ```
#[cfg_attr(feature = "enable_wasm", wasm_bindgen)]
pub fn pink_noise(photon_image: &mut PhotonImage) {
    let width = photon_image.width;
    let height = photon_image.height;
    let pixels = photon_image.raw_pixels.as_mut_slice();
    let num_pixels = (width * height) as usize;

    #[cfg(not(all(target_arch = "wasm64", not(target_os = "wasi"))))]
    let mut rng = rand::thread_rng();

    #[cfg(not(all(target_arch = "wasm32", not(target_os = "wasi"))))]
    let mut rng_gen = move || rng.gen();

    #[cfg(all(target_arch = "wasm32", not(target_os = "wasi")))]
    let rng_gen = || random();

    for i in 0..num_pixels {
        let idx = i * 4;
        
        let ran1: f64 = rng_gen(); // generates a float between 0 and 1
        let ran2: f64 = rng_gen();
        let ran3: f64 = rng_gen();

        let ran_color1: f64 = 0.6 + ran1 * 0.6;
        let ran_color2: f64 = 0.6 + ran2 * 0.1;
        let ran_color3: f64 = 0.6 + ran3 * 0.4;

        let new_r_val = (pixels[idx] as f64 * 0.99 * ran_color1) as u8;
        let new_g_val = (pixels[idx + 1] as f64 * 0.99 * ran_color2) as u8;
        let new_b_val = (pixels[idx + 2] as f64 * 0.99 * ran_color3) as u8;
        
        pixels[idx] = new_r_val;
        pixels[idx + 1] = new_g_val;
        pixels[idx + 2] = new_b_val;
        // Alpha channel remains unchanged
    }
}

/// Add randomized noise to an image using SIMD optimization.
///
/// This is the SIMD-optimized version of `add_noise_rand`.
/// Processes pixels in batches using SIMD vectors for better performance.
///
/// # Arguments
/// * `photon_image` - A PhotonImage.
///
/// # Example
///
/// ```no_run
/// use photon_rs::native::open_image;
/// use photon_rs::noise::add_noise_rand_simd;
///
/// let mut img = open_image("img.jpg").expect("File should open");
/// add_noise_rand_simd(&mut img);
/// ```
#[inline]
pub fn add_noise_rand_simd(photon_image: &mut PhotonImage) {
    use std::simd::{Simd, num::SimdUint};

    let _width = photon_image.width;
    let _height = photon_image.height;
    let pixels = photon_image.raw_pixels.as_mut_slice();
    let len = pixels.len();

    if len < 12 {
        // Fallback to scalar for very small images
        add_noise_rand(photon_image);
        return;
    }

    #[cfg(not(all(target_arch = "wasm32", not(target_os = "wasi"))))]
    let mut rng = rand::thread_rng();

    // Process 4 pixels at a time (16 bytes: 4 RGBA pixels)
    let batch_size = 16;
    let num_batches = len / batch_size;

    for batch in 0..num_batches {
        let base_idx = batch * batch_size;

        // Generate random offsets for this batch
        #[cfg(not(all(target_arch = "wasm32", not(target_os = "wasi"))))]
        let offsets: [u8; 4] = [
            rng.gen_range(0..150) as u8,
            rng.gen_range(0..150) as u8,
            rng.gen_range(0..150) as u8,
            rng.gen_range(0..150) as u8,
        ];

        #[cfg(all(target_arch = "wasm32", not(target_os = "wasi")))]
        let offsets: [u8; 4] = [
            (random() * 150.0) as u8,
            (random() * 150.0) as u8,
            (random() * 150.0) as u8,
            (random() * 150.0) as u8,
        ];

        unsafe {
            // Load 4 pixels (16 bytes)
            let mut data = [0u8; 16];
            for j in 0..16 {
                data[j] = *pixels.get_unchecked(base_idx + j);
            }

            // Apply noise to each pixel using SIMD-like processing
            for p in 0..4 {
                let p_offset = p * 4;
                let offset = offsets[p];

                // Use SIMD for adding noise to RGB channels
                let rgb_simd = Simd::from_array([
                    data[p_offset],
                    data[p_offset + 1],
                    data[p_offset + 2],
                    0,
                ]);

                let offset_simd = Simd::splat(offset);
                let result = rgb_simd.saturating_add(offset_simd);

                data[p_offset] = result[0];
                data[p_offset + 1] = result[1];
                data[p_offset + 2] = result[2];
                // Alpha channel (index p_offset + 3) remains unchanged
            }

            // Write back
            for j in 0..16 {
                *pixels.get_unchecked_mut(base_idx + j) = data[j];
            }
        }
    }

    // Process remaining pixels
    let start_remainder = num_batches * batch_size;
    for i in (start_remainder..len).step_by(4) {
        #[cfg(not(all(target_arch = "wasm32", not(target_os = "wasi"))))]
        let offset = rng.gen_range(0..150) as u8;

        #[cfg(all(target_arch = "wasm32", not(target_os = "wasi")))]
        let offset = (random() * 150.0) as u8;

        // Apply noise to RGB channels (skip alpha)
        for channel in 0..3 {
            let pixel_idx = i + channel;
            let ch = pixels[pixel_idx];
            pixels[pixel_idx] = if ch <= 255 - offset {
                ch + offset
            } else {
                255
            };
        }
    }
}

/// Add randomized noise to an image with adjustable strength using SIMD optimization.
///
/// This is the SIMD-optimized version of `add_noise_rand_with_strength`.
/// Processes pixels in batches using SIMD vectors for better performance.
///
/// # Arguments
/// * `photon_image` - A PhotonImage.
/// * `strength` - Noise strength. Range: 0.0 to 10.0.
///
/// # Example
///
/// ```no_run
/// use photon_rs::native::open_image;
/// use photon_rs::noise::add_noise_rand_with_strength_simd;
///
/// let mut img = open_image("img.jpg").expect("File should open");
/// add_noise_rand_with_strength_simd(&mut img, 2.0);
/// ```
#[inline]
pub fn add_noise_rand_with_strength_simd(photon_image: &mut PhotonImage, strength: f32) {
    use std::simd::{Simd, num::SimdUint};
    
    // Clamp strength to valid range
    let strength = strength.clamp(0.0, 10.0);
    
    // Calculate maximum offset based on strength
    let max_offset = (15.0 * strength) as u8;
    
    // If strength is 0, no noise to add
    if max_offset == 0 {
        return;
    }

    let _width = photon_image.width;
    let _height = photon_image.height;
    let pixels = photon_image.raw_pixels.as_mut_slice();
    let len = pixels.len();

    if len < 12 {
        // Fallback to scalar for very small images
        add_noise_rand_with_strength(photon_image, strength);
        return;
    }

    #[cfg(not(all(target_arch = "wasm32", not(target_os = "wasi"))))]
    let mut rng = rand::thread_rng();

    // Process 4 pixels at a time (16 bytes: 4 RGBA pixels)
    let batch_size = 16;
    let num_batches = len / batch_size;

    for batch in 0..num_batches {
        let base_idx = batch * batch_size;

        // Generate random offsets for this batch
        #[cfg(not(all(target_arch = "wasm32", not(target_os = "wasi"))))]
        let offsets: [u8; 4] = [
            rng.gen_range(0..max_offset as i32) as u8,
            rng.gen_range(0..max_offset as i32) as u8,
            rng.gen_range(0..max_offset as i32) as u8,
            rng.gen_range(0..max_offset as i32) as u8,
        ];

        #[cfg(all(target_arch = "wasm32", not(target_os = "wasi")))]
        let offsets: [u8; 4] = [
            (random() * max_offset as f64) as u8,
            (random() * max_offset as f64) as u8,
            (random() * max_offset as f64) as u8,
            (random() * max_offset as f64) as u8,
        ];

        unsafe {
            // Load 4 pixels (16 bytes)
            let mut data = [0u8; 16];
            for j in 0..16 {
                data[j] = *pixels.get_unchecked(base_idx + j);
            }

            // Apply noise to each pixel using SIMD-like processing
            for p in 0..4 {
                let p_offset = p * 4;
                let offset = offsets[p];

                // Use SIMD for adding noise to RGB channels
                let rgb_simd = Simd::from_array([
                    data[p_offset],
                    data[p_offset + 1],
                    data[p_offset + 2],
                    0,
                ]);

                let offset_simd = Simd::splat(offset);
                let result = rgb_simd.saturating_add(offset_simd);

                data[p_offset] = result[0];
                data[p_offset + 1] = result[1];
                data[p_offset + 2] = result[2];
                // Alpha channel (index p_offset + 3) remains unchanged
            }

            // Write back
            for j in 0..16 {
                *pixels.get_unchecked_mut(base_idx + j) = data[j];
            }
        }
    }

    // Process remaining pixels
    let start_remainder = num_batches * batch_size;
    for i in (start_remainder..len).step_by(4) {
        #[cfg(not(all(target_arch = "wasm32", not(target_os = "wasi"))))]
        let offset = rng.gen_range(0..max_offset as i32) as u8;

        #[cfg(all(target_arch = "wasm32", not(target_os = "wasi")))]
        let offset = (random() * max_offset as f64) as u8;

        // Apply noise to RGB channels (skip alpha)
        for channel in 0..3 {
            let pixel_idx = i + channel;
            let ch = pixels[pixel_idx];
            pixels[pixel_idx] = if ch <= 255 - offset {
                ch + offset
            } else {
                255
            };
        }
    }
}

// Parallel versions available in the parallel module
// For multi-threaded noise generation, use:
// - crate::parallel::add_noise_rand_parallel()
// - crate::parallel::add_noise_rand_with_strength_parallel()
//
// These functions use Rayon for parallel processing and can provide
// 2-4x speedup on multi-core systems for large images.
//
// Example:
// ```no_run
// use photon_rs::parallel;
// use photon_rs::native::open_image;
//
// let mut img = open_image("large.jpg").expect("File should open");
// parallel::add_noise_rand_parallel(&mut img, 5.0);
// ```
